# Generated by Django 5.1.1 on 2024-09-07 09:30

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('hashed_refresh_token', models.CharField(max_length=255)),
                ('last_ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
